import {
  QUEST_OBJECT_CONTRACT_ADDRESS,
  FREE_OBJECT_CONTRACT_ADDRESS,
  PREMIUM_OBJECT_CONTRACT_ADDRESS,
  WALLPAPER_CONTRACT_ADDRESS,
  BASEPLATE_CONTRACT_ADDRESS
} from "./config"

export type ObjectContract =
  typeof QUEST_OBJECT_CONTRACT_ADDRESS |
  typeof FREE_OBJECT_CONTRACT_ADDRESS |
  typeof PREMIUM_OBJECT_CONTRACT_ADDRESS |
  typeof WALLPAPER_CONTRACT_ADDRESS |
  typeof BASEPLATE_CONTRACT_ADDRESS
